apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.angular.dep.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers: 
      - name: angular-app
        image: {{ .Values.angular.dep.angularApp.image.repository }}:{{ .Values.angular.dep.angularApp.image.tag }}
        imagePullPolicy: {{ .Values.angular.dep.angularApp.imagePullPolicy }}
        ports:
        - containerPort: 80
        env:
        {{ toYaml .Values.angular.env | nindent 12 }}
        resources: {}
      imagePullSecrets:
      - name: regcred