apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "springboot.labels" . | nindent 4 }}
type: Opaque
data:
  mysqlPassword: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
  mysqlUser: {{ .Values.mysql.mysqlUser | b64enc | quote }}