apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: emp
  labels:
  {{- include "springboot.labels" . | nindent 4 }}
type: Opaque
data:
  mysqlPassword: {{ .Values.mysql.mysqlPassword | b64enc | quote }}