apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.svc.ports.port }}
      protocol: {{ .Values.svc.ports.protocol }}
      targetPort: {{ .Values.svc.ports.targetPort }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.svc.type }}
