apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "springboot.fullname" . }}-dep
  namespace: emp
  labels:
  {{- include "springboot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dep.replicas }}
  selector:
    matchLabels:
      app: springboot-app
    {{- include "springboot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: springboot-app
      {{- include "springboot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: {{ .Values.mysql.host | quote }}
        - name: DB_PORT
          value: {{ .Values.mysql.service.port | quote }}
        - name: DB_NAME
          value: {{ .Values.mysql.mysqlDatabase | quote }}
        - name: DB_USERNAME
          value: {{ .Values.mysql.mysqlUser | quote }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysqlPassword
        - name: DATABASE_DRIVER
          value: {{ .Values.mysql.mysqlDriver | quote }}       
        image: {{ .Values.dep.springbootApp.image.repository }}:{{ .Values.dep.springbootApp.image.tag }}
        imagePullPolicy: {{ .Values.dep.springbootApp.imagePullPolicy }}
        name: springboot-app
        ports:
        - containerPort: 8080
        resources: {}
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot.fullname" . }}-svc
  namespace: emp
  labels:
  {{- include "springboot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: springboot-app
  {{- include "springboot.selectorLabels" . | nindent 4 }}
  ports:
        {{- .Values.svc.ports | toYaml | nindent 2 -}}
