apiVersion: v1
kind: Service
metadata:
  name: {{ include "springboot.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "springboot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.svc.type }}
  selector:
    app: springboot-app
  {{- include "springboot.selectorLabels" . | nindent 4 }}
  ports:
        {{- .Values.svc.ports | toYaml | nindent 2 -}}
