apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "springboot.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: springboot.dev.neysho.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "springboot.fullname" . }}-svc
                port:
                  number: 8080
