apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.dep.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
      - name: springboot-app   
        image: {{ .Values.dep.springbootApp.image.repository }}:{{ .Values.dep.springbootApp.image.tag }}
        imagePullPolicy: {{ .Values.dep.springbootApp.imagePullPolicy }}
        ports:
        - containerPort: 8080
        env:
        {{- toYaml .Values.dep.env | nindent 12 }}
        resources: {}
      imagePullSecrets:
      - name: regcred