apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.svc.port }}
      protocol: {{ .Values.svc.protocol }}
      targetPort: {{ .Values.svc.targetPort }}
  selector:
    app: {{ .Release.Name }}-backend
  type: {{ .Values.svc.type }}
