apiVersion: v2
name: employee-management
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"


dependencies:
  - name: mysql
    version: 9.4.1
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
    alias: mysql