
namespace: emp

dep:
  replicas: 1
  springbootApp:
    image:
      repository: neysho/emp-backend
      tag: "1"
    imagePullPolicy: Always
svc:
  port: 8080
  protocol: TCP
  targetPort: 8080
  type: NodePort
  
serviceAccount:
  create: true
  name: helm-serviceaccount

rbac:
  create: true

mysql:
  namespace: emp  # Specify the desired namespace
  image: mysql:5.7
  host: mysql  
  mysqlRootPassword: root
  mysqlDatabase: bsisa 
  mysqlUser: root
  mysqlPassword: root
  service:
    port: 3306

angular-dep:
  replicas: 1
  angularApp:
    image:
      repository: neysho/emp-frontend
      tag: "1"
    imagePullPolicy: Always
angular-svc:
  port: 80
  protocol: TCP
  targetPort: 80
  type: NodePort  