
namespace: emp

dep:
  replicas: 1
  springbootApp:
    image:
      repository: neysho/emp-backend
      tag: "1"
    imagePullPolicy: Always
svc:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: NodePort
  
serviceAccount:
  create: true
  name: helm-serviceaccount

rbac:
  create: true

mysql:
  enabled: true
  host: mysql  
  mysqlDriver: mysql
  mysqlRootPassword: root
  mysqlDatabase: bsisa 
  mysqlUser: admin
  mysqlPassword: root
  service:
    port: 3306    
  initdbScripts:
    initdb.sql: |-
      CREATE DATABASE IF NOT EXISTS bsisa DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
      CREATE USER 'admin'@'%' IDENTIFIED BY 'root';
      GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
      FLUSH PRIVILEGES;
  volumePermissions:
    enabled: true
  persistence:
    enabled: true
    storageClass: local-storage  # Specify your desired storage class
    accessModes:
      - ReadWriteOnce  # Adjust as needed
    size: 3Gi  # Adjust the size according to your requirements    
    existingClaim: ""  # If using an existing PVC, specify its name here
    mountPath: /mnt/mysql  # Specify the desired mount path for the volume
    nodeAffinity:  # Add node affinity rules here if needed
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker2
  # primary:    
  #   persistence:
  #     enabled: true
  #     storageClass: local-storage
  #     accessMode: ReadWriteOnce
  #     size: 3Gi