
namespace: emp

dep:
  replicas: 1
  springbootApp:
    image:
      repository: neysho/emp-backend
      tag: "1"
    imagePullPolicy: Always
    env:
    - name: FRONTEND_INGRESS
      value: emp.dev.neysho.com
    - name: DB_HOST
      value: mysql
    - name: DB_PORT
      value: 3306
    - name: DB_NAME
      value: bsisa
    - name: DB_USERNAME
      value: root
    - name: DB_PASSWORD
      value: root
    
svc:
  port: 8080
  protocol: TCP
  targetPort: 8080
  type: ClusterIP
  
serviceAccount:
  create: true
  name: helm-serviceaccount

rbac:
  create: true

mysql:
  namespace: emp  # Specify the desired namespace
  image: mysql:5.7
  host: mysql  
  mysqlRootPassword: root
  mysqlDatabase: bsisa 
  mysqlUser: root
  mysqlPassword: root
  service:
    port: 3306

angular:
  dep:
    replicas: 1
    angularApp:
      image:
        repository: neysho/emp-frontend
        tag: "1"
      imagePullPolicy: Always
  svc:
    port: 80
    protocol: TCP
    targetPort: 80
    type: ClusterIP  
  env: # Add the environment variable here
  - name: BACKEND_INGRESS
    value: emp.dev.neysho.com/backend

      